#!/bin/bash

set -e
set -v
set -x

git clone 'https://github.com/geodynamics/aspect.git'

mkdir 'aspect/build'

cd 'aspect/build'

git checkout v2.0.0

cmake \
  -G Ninja \
  -D CMAKE_INSTALL_PREFIX="${HOME}/.local" \
  ..

cmake \
  --build . \
  -- \
  all \
  install

echo 'export PATH="${HOME}/.local/bin:${PATH}"' \
  > "${HOME}/.profile"
